services:
  sql-backup:
    image: ${DOCKER_REGISTRY}sql-backup:${DOCKER_TAG:-latest}
    init: true
    restart: unless-stopped
    environment:
      REMOTE_BACKUP_DIR: "${REMOTE_BACKUP_DIR:?}"
      LOCAL_BACKUP_DIR: "/root/sql/${LOCAL_BACKUP_DIR:?}"
      DB_ADDRESS: "${DB_ADDRESS:?}"
      SA_PASSWORD: "${DB_PASSWORD:?}"
      DB_NAME: "${DB_NAME:?}"
      ROOT_FOLDER_ID: "${DRIVE_FOLDER_ID:?}"
    volumes:
      - "sqldata:/root/sql"
    networks:
      - sqlnetwork
    secrets:
      - source: drive-key
        target: /root/drive_key.json

volumes:
  sqldata:
    external: true
    name: "${DOCKER_VOLUME:?}"

networks:
  sqlnetwork:
    external: true
    name: "${DOCKER_NETWORK:?}"

secrets:
  drive-key:
    file: ./secrets/drive_key.json
